name: Build iOS Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Install CocoaPods
      run: gem install cocoapods

    - name: Lint Podspec (Compile Library)
      working-directory: react-native-open-face
      # We skip dependencies to avoid needing a full RN app just for linting
      run: pod lib lint OpenFace.podspec --allow-warnings --skip-import-validation
